parameters:
    wrep.fosuserbundlemandrillmailer.class: Wrep\FOSUserBundleMandrillMailer\Mandrill\FOSUserBundleMailer
    wrep.fosuserbundlemandrillmailertwig.class: Wrep\FOSUserBundleMandrillMailer\Mandrill\FOSUserBundleMailerTwig
    wrep.hip_mandrill.dispatcher.class: Hip\MandrillBundle\Message

services:
    wrep.hip_mandrill.message:
        class: %wrep.hip_mandrill.dispatcher.class%

    wrep.fosuserbundlemandrillmailer:
         class: %wrep.fosuserbundlemandrillmailer.class%
         arguments:
             - @router
             - @templating
             - @hip_mandrill.dispatcher
             - @wrep.hip_mandrill.message
             - { confirmation.template: %fos_user.registration.confirmation.template%, resetting_password.template: %fos_user.resetting.email.template% }

    wrep.fosuserbundlemandrillmailer:
         class: %wrep.fosuserbundlemandrillmailertwig.class%
         arguments:
             - @router
             - @templating
             - @hip_mandrill.dispatcher
             - @wrep.hip_mandrill.message
             - @twig
             - { confirmation.template: %fos_user.registration.confirmation.template%, resetting_password.template: %fos_user.resetting.email.template% }